/*
 * This header provides macros for at91 dma bindings.
 *
 * Copyright (C) 2013 Ludovic Desroches <ludovic.desroches@atmel.com>
 *
 * GPLv2 only
 */

#ifndef __DT_BINDINGS_AT91_DMA_H__
#define __DT_BINDINGS_AT91_DMA_H__

/* ---------- HDMAC ---------- */

/*
 * Source and/or destination peripheral ID
 */
#define AT91_DMA_CFG_PER_ID_MASK	(0xff)
#define AT91_DMA_CFG_PER_ID(id)		(id & AT91_DMA_CFG_PER_ID_MASK)

/*
 * FIFO configuration: it defines when a request is serviced.
 */
#define AT91_DMA_CFG_FIFOCFG_OFFSET	(8)
#define AT91_DMA_CFG_FIFOCFG_MASK	(0xf << AT91_DMA_CFG_FIFOCFG_OFFSET)
#define AT91_DMA_CFG_FIFOCFG_HALF	(0x0 << AT91_DMA_CFG_FIFOCFG_OFFSET)	/* half FIFO (default behavior) */
#define AT91_DMA_CFG_FIFOCFG_ALAP	(0x1 << AT91_DMA_CFG_FIFOCFG_OFFSET)	/* largest defined AHB burst */
#define AT91_DMA_CFG_FIFOCFG_ASAP	(0x2 << AT91_DMA_CFG_FIFOCFG_OFFSET)	/* single AHB access */


/* ---------- XDMAC ---------- */
#define AT91_XDMAC_DT_MEM_IF_MASK	(0x1)
#define AT91_XDMAC_DT_MEM_IF_OFFSET	(13)
#define AT91_XDMAC_DT_MEM_IF(mem_if)	(((mem_if) & AT91_XDMAC_DT_MEM_IF_MASK) \
					<< AT91_XDMAC_DT_MEM_IF_OFFSET)
#define AT91_XDMAC_DT_GET_MEM_IF(cfg)	(((cfg) >> AT91_XDMAC_DT_MEM_IF_OFFSET) \
					& AT91_XDMAC_DT_MEM_IF_MASK)

#define AT91_XDMAC_DT_PER_IF_MASK	(0x1)
#define AT91_XDMAC_DT_PER_IF_OFFSET	(14)
#define AT91_XDMAC_DT_PER_IF(per_if)	(((per_if) & AT91_XDMAC_DT_PER_IF_MASK) \
					<< AT91_XDMAC_DT_PER_IF_OFFSET)
#define AT91_XDMAC_DT_GET_PER_IF(cfg)	(((cfg) >> AT91_XDMAC_DT_PER_IF_OFFSET) \
					& AT91_XDMAC_DT_PER_IF_MASK)

#define AT91_XDMAC_DT_PERID_MASK	(0x7f)
#define AT91_XDMAC_DT_PERID_OFFSET	(24)
#define AT91_XDMAC_DT_PERID(perid)	(((perid) & AT91_XDMAC_DT_PERID_MASK) \
					<< AT91_XDMAC_DT_PERID_OFFSET)
#define AT91_XDMAC_DT_GET_PERID(cfg)	(((cfg) >> AT91_XDMAC_DT_PERID_OFFSET) \
					& AT91_XDMAC_DT_PERID_MASK)

/* Peripheral DMA-channel definitions - see table 37-2 in SAMA5D2 Series datasheet (DS60001476C) */
#define AT91_DMA_CHAN_TWIHS0_TX     (AT91_XDMAC_DT_PERID(0))
#define AT91_DMA_CHAN_TWIHS0_RX     (AT91_XDMAC_DT_PERID(1))
#define AT91_DMA_CHAN_TWIHS1_TX     (AT91_XDMAC_DT_PERID(2))
#define AT91_DMA_CHAN_TWIHS1_RX     (AT91_XDMAC_DT_PERID(3))
#define AT91_DMA_CHAN_QSPI0_TX      (AT91_XDMAC_DT_PERID(4))
#define AT91_DMA_CHAN_QSPI0_RX      (AT91_XDMAC_DT_PERID(5))
#define AT91_DMA_CHAN_SPI0_TX       (AT91_XDMAC_DT_PERID(6))
#define AT91_DMA_CHAN_SPI0_RX       (AT91_XDMAC_DT_PERID(7))
#define AT91_DMA_CHAN_SPI1_TX       (AT91_XDMAC_DT_PERID(8))
#define AT91_DMA_CHAN_SPI1_RX       (AT91_XDMAC_DT_PERID(9))
#define AT91_DMA_CHAN_PWM_TX        (AT91_XDMAC_DT_PERID(10))
#define AT91_DMA_CHAN_FLEXCOM0_TX   (AT91_XDMAC_DT_PERID(11))
#define AT91_DMA_CHAN_FLEXCOM0_RX   (AT91_XDMAC_DT_PERID(12))
#define AT91_DMA_CHAN_FLEXCOM1_TX   (AT91_XDMAC_DT_PERID(13)
#define AT91_DMA_CHAN_FLEXCOM1_RX   (AT91_XDMAC_DT_PERID(14))
#define AT91_DMA_CHAN_FLEXCOM2_TX   (AT91_XDMAC_DT_PERID(15))
#define AT91_DMA_CHAN_FLEXCOM2_RX   (AT91_XDMAC_DT_PERID(16))
#define AT91_DMA_CHAN_FLEXCOM3_TX   (AT91_XDMAC_DT_PERID(17))
#define AT91_DMA_CHAN_FLEXCOM3_RX   (AT91_XDMAC_DT_PERID(18))
#define AT91_DMA_CHAN_FLEXCOM4_TX   (AT91_XDMAC_DT_PERID(19))
#define AT91_DMA_CHAN_FLEXCOM4_RX   (AT91_XDMAC_DT_PERID(20))
#define AT91_DMA_CHAN_SSC0_TX       (AT91_XDMAC_DT_PERID(21))
#define AT91_DMA_CHAN_SSC0_RX       (AT91_XDMAC_DT_PERID(22))
#define AT91_DMA_CHAN_SSC1_TX       (AT91_XDMAC_DT_PERID(23))
#define AT91_DMA_CHAN_SSC1_RX       (AT91_XDMAC_DT_PERID(24))
#define AT91_DMA_CHAN_ADC_RX        (AT91_XDMAC_DT_PERID(25))
#define AT91_DMA_CHAN_AES_TX        (AT91_XDMAC_DT_PERID(26))
#define AT91_DMA_CHAN_AES_RX        (AT91_XDMAC_DT_PERID(27))
#define AT91_DMA_CHAN_TDES_TX       (AT91_XDMAC_DT_PERID(28))
#define AT91_DMA_CHAN_TDES_RX       (AT91_XDMAC_DT_PERID(29))
#define AT91_DMA_CHAN_SHA_TX        (AT91_XDMAC_DT_PERID(30))
#define AT91_DMA_CHAN_ISC0_TX       (AT91_XDMAC_DT_PERID(31))
#define AT91_DMA_CHAN_ISC0_RX       (AT91_XDMAC_DT_PERID(32))
#define AT91_DMA_CHAN_ISC1_TX       (AT91_XDMAC_DT_PERID(33))
#define AT91_DMA_CHAN_ISC1_RX       (AT91_XDMAC_DT_PERID(34))
#define AT91_DMA_CHAN_UART0_TX      (AT91_XDMAC_DT_PERID(35))
#define AT91_DMA_CHAN_UART0_RX      (AT91_XDMAC_DT_PERID(36))
#define AT91_DMA_CHAN_UART1_TX      (AT91_XDMAC_DT_PERID(37))
#define AT91_DMA_CHAN_UART1_RX      (AT91_XDMAC_DT_PERID(38))
#define AT91_DMA_CHAN_UART2_TX      (AT91_XDMAC_DT_PERID(39))
#define AT91_DMA_CHAN_UART2_RX      (AT91_XDMAC_DT_PERID(40))
#define AT91_DMA_CHAN_UART3_TX      (AT91_XDMAC_DT_PERID(41))
#define AT91_DMA_CHAN_UART3_RX      (AT91_XDMAC_DT_PERID(42))
#define AT91_DMA_CHAN_UART4_TX      (AT91_XDMAC_DT_PERID(43))
#define AT91_DMA_CHAN_UART4_RX      (AT91_XDMAC_DT_PERID(44))
#define AT91_DMA_CHAN_TC0_RX        (AT91_XDMAC_DT_PERID(45))
#define AT91_DMA_CHAN_TC1_RX        (AT91_XDMAC_DT_PERID(46))
#define AT91_DMA_CHAN_CLASSD_TX     (AT91_XDMAC_DT_PERID(47))
#define AT91_DMA_CHAN_QSPI1_TX      (AT91_XDMAC_DT_PERID(48))
#define AT91_DMA_CHAN_QSPI1_RX      (AT91_XDMAC_DT_PERID(49))
#define AT91_DMA_CHAN_PMDIC_RX      (AT91_XDMAC_DT_PERID(50))

#endif /* __DT_BINDINGS_AT91_DMA_H__ */
